### ISSUE TITLE
Configure Stock Synthesis build in Jenkins

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nwfsc-fram/boatnet#1232]
- [x] Pass credentials required to IT to add to Jenkins
- [x] Verify git pull from vlab works
- [x] Dry run of  ADMB build using https://github.com/admb-project/admb/tree/master/examples/admb/simple build
   * Installed build-essential apt package (g++)
- [x] Sanity check - build SS code in virtualbox (using .sh script)
  * required minor change to Make_SS_330.sh (comment out cd command and add BUILD_DIR env variable)
  * Did not build correctly with admb version 12.1 (```error: ‘save_gradients’ was not declared in this scope```) or on ubuntu 18.04. Built correctly on ubuntu 16.04 with the 12.0 admb .deb package installer.
- [x] Create Docker image (ubuntu 16.04 + build-essential + admb 12.0 .deb installed) + test build
  * configure environment so script runs without modifications (clone to vlab/stock-synthesis, copy build script to ../.. path, and create BUILD_DIR env variable)
- [x] Build SS code in Docker image (using .sh script)
- [x] Verify validity of output binary

**Comment by iantaylor-NOAA** [comment]
Thanks for working on this @wsmith-nwfsc and @SaOgaz-NOAA. I've been using ADMB for many years, so please let me know if I can help debug any installation issues you might have.

**Comment by wsmith-nwfsc** [comment]
Jenkins now configured (after some weird Jenkins bugs popping up) and vlab source pull is working.
Proceeding with build steps...

**Comment by SaOgaz-NOAA** [comment]
Hey @wsmith-nwfsc how is this going? Anything I can help with?

**Comment by wsmith-nwfsc** [comment]
The source pull is working correctly, next steps are outlined in the description. Hoping to get to this week, but if you want you can try getting ADMB to run on a simple ubuntu docker image (I was going to run on a 18.04 VM as a sanity check next.)

**Comment by wsmith-nwfsc** [comment]
The stock-synthesis-build is now running on our Jenkins server and spitting out a valid ```ss``` executable.
Following up with Kathryn...

**Comment by wsmith-nwfsc** [comment]
Continuing this project here: #1257
